### ISSUE TITLE
How to create a document for HTTP POST?

### ISSUE THREAD

**Issue by circleupx** [muellerbbm-vas/grivet#107]
Hey @danielmenzel
 
Quick question, I am using grivet to integrate against an API that implements the JSON:API specification, everything works as expected, I am able to retrieve data from the API using grivet. 

I would like to submit an HTTP POST request against the API using grivet but I am little lost as to how I should go about doing that, I did not find any documentation and by looking at the unit test here in grivet it would appear that the best way to do it would be like this,

```typescript
// Build a JSON:API Document using ClientDocument 
const doc = new JsonApi.ClientDocument('users');
    doc.setAttribute('name', 'yunier');


// Then create a raw document as  class Document in JsonApi module takes 
// Spec.JsonApiDocument in the constructor. 
    const rawDoc: Spec.JsonApiDocument = {
      data: {
        id: '1',
      type: doc.data.data.type,
      attributes: doc.data.data.attributes
      }
    };

// The finally, our Context has an HTTP POST method. 
// This method is called and the raw document is passed through.
 postDocument(url: URL, doc: Spec.JsonApiDocument): Promise<Spec.JsonApiDocument> {
    return this.http.post<Spec.JsonApiDocument>(url.href, doc).toPromise();
  }
```

The code above works, I **can create** resources against the API, but I feel like I am missing something, like the code above is not right and that there is an easier way to create resources using grivet. 

Please, let me know.

**Update**

After posting, I noticed that the code can be simplified to this, 

```typescript
// Build a JSON:API Document using ClientDocument 
const doc = new JsonApi.ClientDocument('users');
    doc.setAttribute('name', 'yunier');

// The finally, our Context has an HTTP POST method. 
 postDocument(url: URL, doc: Spec.ClientJsonApiDocument): Promise<Spec.JsonApiDocument> {
    return this.http.post<Spec.JsonApiDocument>(url.href, doc).toPromise();
  }
```

**Comment by danielmenzel** [comment]
Hi,
you are right, at the moment, POSTing documents is not the focus of grivet and therefore not well thought out or documented. The way you do it seems reasonable though.

**Comment by circleupx** [comment]
Perfect, thank you.

**Comment by MartenBE** [comment]
Thank you, I was looking for this. Perhaps the updated snippet can be included in the readme?

**Comment by danielmenzel** [comment]
Good idea, I published a new version with updated readme and reference documentation.
