### ISSUE TITLE
Include tslib as a dependency

### ISSUE THREAD

**Issue by htcicek** [muellerbbm-vas/grivet#469]
running tsc introduces `tslib` as a requirement at `lib/index.js`
```js
const tslib_1 = require("tslib");
```

Seems to be related to the memoized decorator.

**Comment by danielmenzel** [comment]
Thanks for the hint, we'll look into it

**Comment by danielmenzel** [comment]
Instead of adding a new dependency in `package.json`, we decided to remove the `importHelpers` directive in `tsconfig.json`, which introduced the dependency in the first place.
